apiVersion: v1
kind: Secret
metadata:
  name: repo-2048
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  name: "2048"
  url: https://github.com/eminalemdar/2048
